app/db_crud/forms.py
# -*- coding: utf-8 -*-
"""Public forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField,SubmitField
from wtforms.validators import DataRequired

from models.Models import Sensor


class SensorData(FlaskForm):
    type = SubmitField("Sensor")

'''
class LoginForm(FlaskForm):
    """Login form."""

    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append("Unknown username")
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append("Invalid password")
            return False

        if not self.user.active:
            self.username.errors.append("User not activated")
            return False
        return True
'''

app/__init__.py
import imp
import os
from re import I
from flask import Flask
from flask import Blueprint
#from ..db import Session
from .main import main 
from .db_crud import db_crud
#main = Blueprint('main',__name__)

def create_app():#(config_name):
	app = Flask(__name__)
	#app.config.from_object()
	app.register_blueprint(main)
	app.register_blueprint(db_crud)
	app.config['SECRET_KEY'] = os.urandom(32)
	return app

app/db_crud/__init__.py
# -*- coding: utf-8 -*-
"""The database CRUD module, including the CRUD and user auth."""
from flask import Blueprint
db_crud = Blueprint('db_crud',__name__,static_folder="../static")

from . import views  # noqa

app/db_crud/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from crypt import methods
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

from app.db_crud.forms import SensorData
from . import db_crud

@db_crud.route("/", methods=["GET", "POST"])
def home():
    """Home page."""
    #current_app.logger.info("Hello from the home page!")
    # Handle logging in 
    return render_template("db_crud/home.html")

@db_crud.route("/about/")
def about():
    return render_template('db_crud/about.html')

@db_crud.route("/CRUD/", methods=["GET","POST"])
def crud():
    form = SensorData()
    return render_template('db_crud/crud.html', form = form)

'''
@blueprint.route("/logout/")
@login_required
def logout():
    """Logout."""
    logout_user()
    flash("You are logged out.", "info")
    return redirect(url_for("db_crud.home"))


@blueprint.route("/register/", methods=["GET", "POST"])
def register():
    """Register new user."""
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        User.create(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
            active=True,
        )
        flash("Thank you for registering. You can now log in.", "success")
        return redirect(url_for("db_crud.home"))
    else:
        flash_errors(form)
    return render_template("db_crud/register.html", form=form)


@blueprint.route("/about/")
def about():
    """About page."""
    form = LoginForm(request.form)
    return render_template("db_crud/about.html", form=form)

@blueprint.route("/search/",methods=['GET', 'POST'])
def search():    
    """search."""
    db = SQLManager()
    data = db.showversion()
    #print(data)
    db.close()
    return render_template("db_crud/search.html", data = data) 
'''

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import hello

app/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('db_crud.home')}}">log in</a> or
            <a href="{{ url_for('db_crud.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

app/templates/db_crud/about.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <h1 class="mt-5">About</h1>
    <div class="row">
      <p class="lead">This template was created by <a href="http://github.com/sloria/">Steven Loria</a> for use with the <a href="http://github.com/audreyr/cookiecutter/">cookiecutter</a> package by <a href="http://github.com/audreyr/">Audrey Roy</a>.</p>
    </div>
</div>
{% endblock %}

app/templates/db_crud/crud.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
    <h1 class="mt-5">Search</h1>
    <div class="row">
      <p class="lead"> searching for componments information </p>
    </div>
</div>

 <div class="container">
    <h1>Hello, !</h1>
    <div class="col-md-4">
{{ wtf.quick_form(form) }}
</div>
</div>
{% endblock %}

app/templates/db_crud/hello.html
<h1>v1 Hello World!</h1>

app/templates/db_crud/home.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
    
      <h1 class="display-3">Welcome to HGTDPDB</h1>
    
      <p>A demo web application of HGTD production database.</p>
    </div>
</div><!-- /.jumbotron -->

<br />
<br />
  
<div class="display" align="center">
<title> img test </title>
<img alt="hgtd detector" src="{{url_for('static',filename='images/fig_003.png')}}" width="40%"/>
</div>

<br />
<br />

<!-- <div class="row">
    <div class="col-lg-4">
      <h2><i class="fa fa-flask"></i> Bootstrap 4</h2>
      <p>Sleek, intuitive, and powerful mobile-first front-end framework for faster and easier web development.</p>
      <p><a class="btn btn-outline-secondary" href="http://getbootstrap.com/">Official website &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2><i class="fa fa-flask"></i> SQLAlchemy</h2>
      <p>SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.</p>
      <p><a href="http://www.sqlalchemy.org/" class="btn btn-outline-secondary">Official website &raquo;</a></p>
   </div>
    <div class="col-lg-4">
      <h2><i class="fa fa-edit"></i> WTForms</h2>
      <p>WTForms is a flexible forms validation and rendering library for python web development.</p>
      <p><a href="http://wtforms.simplecodes.com/" class="btn btn-outline-secondary">Official website &raquo;</a></p>
    </div>
  
</div> -->
<div class="display" align="right">
<title> img test </title>
<img alt="hgtd detector" src="{{url_for('static',filename='images/CERN.png')}}" width="10%"/>
</div>
{% endblock %}

app/templates/db_crud/register.html
{% extends "layout.html" %}
{% block content %}
<div class="container-narrow">
  <h1 class="mt-5">Register</h1>
    <br/>
    <form id="registerForm" class="form form-register" method="POST" action="" role="form">
           {{ form.csrf_token }}
            <div class="form-group">
                {{form.username.label}}
                {{form.username(placeholder="Username", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.email.label}}
                {{form.email(placeholder="Email", class_="form-control")}}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                {{form.password.label}}
                {{form.password(placeholder="Password", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.confirm.label}}
                {{form.confirm(placeholder="Password (again)", class_="form-control")}}
            </div>
            <p><input class="btn btn-primary" type="submit" value="Register"></p>
    </form>
    <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
</div>
{% endblock %}

app/templates/db_crud/search.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <h1 class="mt-5">Search</h1>
    <div class="row">
      <p class="lead"> searching senor information </p>
    </div>
</div>

<div class="sensor data">

<title>Title</title>
 
    <table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Sensor</th>
        <th>Vendor</th>
        <th>RunNumber</th>
        <th>LeackageCurrent</th>
        <th>BreakDownVoltage</th>
        <th>IVCurve</th>
    </tr>
        {% for i in data %}
            <tr>
                <td>{{ i['ID'] }}</td>
                <td>{{ i['Sensor'] }}</td>
                <td>{{ i['Vendor'] }}</td>
                <td>{{ i['RunNumber'] }}</td>
                <td>{{ i['LeackageCurrent'] }}</td>
                <td>{{ i['BreakDownVoltage'] }}</td>
                <td>{{ i['IVCurve'] }}</td>

            </tr>
        {% endfor %}
    </table>
 
</div>
{% endblock %}

app/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© HGTDPDB</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('db_crud.about') }}">About</a></li>

      <li><a href="mailto:976144544@qq.com">Contact</a></li>
    </ul>
  </small>
</footer>

app/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block title %} 
      HGTDPDB
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
  <a class="navbar-brand" href="{{ url_for('db_crud.home') }}">
     HGTDPDB 
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('db_crud.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('db_crud.about') }}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('db_crud.crud') }}">CRUD TEST</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('db_crud.logout') }}">Logged out
          <i class="fa fa-sign-out-alt"></i>
        </a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome {{ current_user.username }}</h1>
        <h3>This is the members-only page.</h3>
    </div>
{% endblock %}